# Generated by Django 6.0 on 2026-01-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'proekt',
                'verbose_name_plural': 'portfolio',
            },
        ),
    ]
