# Generated by Django 6.0 on 2026-01-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(default='portfolio_images/default.png', upload_to='portfolio_images/'),
        ),
    ]
