# Generated by Django 6.0 on 2026-01-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='img',
        ),
    ]
