# Generated by Django 6.0 on 2026-01-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=30)),
                ('study_year', models.IntegerField(verbose_name='O‘qish yili')),
                ('study_about', models.TextField()),
            ],
            options={
                'verbose_name': "O'qish",
                'verbose_name_plural': 'Kurs',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_year', models.IntegerField(verbose_name='O‘qish yili')),
                ('company_about', models.TextField()),
            ],
            options={
                'verbose_name': 'Tajriba',
                'verbose_name_plural': 'Ish',
            },
        ),
    ]
