# Generated by Django 6.0 on 2026-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_resumeeducation_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='git_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_year',
            field=models.IntegerField(verbose_name='ish yili'),
        ),
    ]
