# Generated by Django 6.0 on 2026-01-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_git_url_alter_workexperience_company_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='Portfolio/')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(verbose_name='Telefon nomer')),
                ('brithday', models.DateField(blank=True, help_text='Please use the format YYYY-MM-DD', null=True)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
