# Generated by Django 6.0 on 2026-01-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profileedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileedit',
            name='phone_number',
            field=models.BigIntegerField(max_length=18, verbose_name='Telefon nomer'),
        ),
    ]
