# Generated by Django 6.0 on 2026-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_profileedit_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileedit',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='Telefon nomer'),
        ),
    ]
